src/Entity/Car.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CarRepository;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CarRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields:['model'], message:"Un tel modèle existe déjà dans notre store, merci de le modifier.")]


class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez renseigner le modèle du véhicule")]
    private ?string $model = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez renseigner la marque du véhicule")]
    private ?string $brand = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    #[Assert\Url(message:"Url invalide")]
    private ?string $coverImage = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Veuillez renseigner le kilométrage du véhicule")]
    private ?int $km = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Veuillez renseigner le prix du véhicule")]
    private ?float $price = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Veuillez renseigner le nombre de propriétaires du véhicule")]
    private ?int $owners = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Veuillez renseigner la cylindrée du véhicule")]
    private ?float $cylinder = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Veuillez renseigner la puissance du véhicule")]
    private ?int $power = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez renseigner le type de carburant consommé par le véhicule")]
    private ?string $carburant = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Veuillez renseigner l'année de mise en circulation du véhicule")]
    private ?int $year = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez renseigner le type de transmission du véhicule")]
    private ?string $transmission = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(min: 50, minMessage:"La description doit faire plus de 50 caractères.")]
    private ?string $content = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(min: 50, minMessage:"Vos options doivent faire plus de 50 caractères.")]
    private ?string $options = null;

    #[ORM\OneToMany(mappedBy: 'car', targetEntity: Images::class, orphanRemoval: true)]
    #[Assert\Valid()]
    private Collection $images;

    #[ORM\ManyToOne(inversedBy: 'cars')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    /**
     * init "slugification"
     *
     * @return void
     */
    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initializeSlug(): void
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            //slugifier la marque et le modèle pour créer un slug "combiné"
            $brandSlug = $slugify->slugify($this->brand);
            $modelSlug = $slugify->slugify($this->model);

            $this->slug = $brandSlug . '-' . $modelSlug;
        }
    }

    /**
     * Afficher la dénomination complète du véhicule
     *
     * @return string
     */
    public function getFullBrand(): string
    {
        return $this->brand." ".$this->model;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): static
    {
        $this->model = $model;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): static
    {
        $this->brand = $brand;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): static
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getKm(): ?int
    {
        return $this->km;
    }

    public function setKm(int $km): static
    {
        $this->km = $km;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getOwners(): ?int
    {
        return $this->owners;
    }

    public function setOwners(int $owners): static
    {
        $this->owners = $owners;

        return $this;
    }

    public function getCylinder(): ?float
    {
        return $this->cylinder;
    }

    public function setCylinder(float $cylinder): static
    {
        $this->cylinder = $cylinder;

        return $this;
    }

    public function getPower(): ?int
    {
        return $this->power;
    }

    public function setPower(int $power): static
    {
        $this->power = $power;

        return $this;
    }

    public function getCarburant(): ?string
    {
        return $this->carburant;
    }

    public function setCarburant(string $carburant): static
    {
        $this->carburant = $carburant;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): static
    {
        $this->year = $year;

        return $this;
    }

    public function getTransmission(): ?string
    {
        return $this->transmission;
    }

    public function setTransmission(string $transmission): static
    {
        $this->transmission = $transmission;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getOptions(): ?string
    {
        return $this->options;
    }

    public function setOptions(string $options): static
    {
        $this->options = $options;

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setCar($this);
        }

        return $this;
    }

    public function removeImage(Images $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getCar() === $this) {
                $image->setCar(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }
}

src/Form/CarType.php
<?php

namespace App\Form;

use App\Entity\Car;
use App\Form\ImageType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class CarType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('model', TextType::class, $this->getConfiguration('Modèle', 'Exemple : Giulia'))
            ->add('brand', TextType::class, $this->getConfiguration('Marque', 'Exemple : Alfa Romeo'))
            ->add('slug', TextType::class, $this->getConfiguration('Slug', 'Adresse web (automatique)',[
                'required' => false
            ]))
            ->add('coverImage', UrlType::class, $this->getConfiguration('Image de couverture', 'Veuillez fournir un URL valide'))
            ->add('km', IntegerType::class, $this->getConfiguration('Kilomètrage', 'Indiquez le nombre de kilomètres du véhicule...'))
            ->add('price', MoneyType::class, $this->getConfiguration('Prix', 'Indiquez le prix du véhicule...'))
            ->add('owners', IntegerType::class, $this->getConfiguration('Nombre de propriétaires', 'Indiquez le nombre de propriétaires du véhicule...'))
            ->add('cylinder', NumberType::class, $this->getConfiguration('Cylindrée', 'Indiquez la cylindrée du véhicule...'))
            ->add('power', IntegerType::class, $this->getConfiguration('Puissance', 'Indiquez la puissance en chevaux du véhicule...'))
            ->add('carburant', ChoiceType::class, [
                'choices'=>[
                    //options = visuel, valeur = dans la bdd
                    'Essence'=>'essence',
                    'Diesel'=>'diesel',
                    'Electrique'=>'electrique',
                    'Hybride'=>'hybride',
                    'LPG'=>'lpg',
                    'CNG'=>'cng',
                ]])
            ->add('year', IntegerType::class, $this->getConfiguration('Année de mise en circulation', 'Indiquez l\'année de mise en circulation du véhicule...'))
            ->add('transmission', ChoiceType::class, [
                'choices'  => [
                    'Automatique' => 'Automatique',
                    'Manuel' => 'Manuel',
                ]])
            ->add('content', TextareaType::class, $this->getConfiguration('Description', 'Décrivez le véhicule'))
            ->add('options', TextareaType::class, $this->getConfiguration('Options', 'Listez les options du véhicule'))
            ->add('images', CollectionType::class,[
                'entry_type'=> ImageType::class,
                'allow_add'=> true,
                'allow_delete'=>true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Car::class,
        ]);
    }
}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Form\CarType;
use App\Entity\Images;
use App\Repository\CarRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\ExpressionLanguage\Expression;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CarController extends AbstractController
{
    /**
     * Afficher toutes les voitures
     *
     * @param CarRepository $repo
     * @return Response
     */
    #[Route('/cars', name: 'cars_index')]
    public function index(CarRepository $repo): Response
    {
        $cars = $repo->findAll();

        return $this->render('cars/index.html.twig', [
            'cars' => $cars,
        ]);
    }

    /**
     * Ajout d'une voiture
     *
     * @return Response
     */
    #[Route("/cars/new", name:"cars_create")]
    #[IsGranted('ROLE_USER')]
    public function create(Request $request, EntityManagerInterface $manager): Response
    {
        $car = new Car();

        
        $form = $this->createform(CarType::class, $car);

        //traitement des données - associations aux champs respectifs - validation
        $form->handleRequest($request);

        //form complet et valid -> envoi bdd + message et redirection
        if($form->isSubmitted() && $form->IsValid())
        {
            //gestion des images
            foreach($car->getImages() as $image)
            {
                $image->setCar($car);
                $manager->persist($image);
            }

            $car->setAuthor($this->getUser());

            $manager->persist($car);
            $manager->flush();

            $this->addFlash(
                'success',
                "La fiche de <strong>".$car->getBrand()." ".$car->getModel()."</strong> a bien été enregistrée."
            );

            return $this->redirectToRoute('cars_show', [
                'slug'=> $car->getSlug()
            ]);
        }

        return $this->render("cars/new.html.twig",[
            'myForm' => $form->createView()
        ]);

    }


    /**
     * Éditer une voiture
     *
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @param Car $car
     * @return Response
     */
    #[Route("cars/{slug}/edit", name:"cars_edit")]
    #[IsGranted(
        attribute: new Expression('(user === subject and is_granted("ROLE_USER")) or is_granted("ROLE_ADMIN")'),
        subject: new Expression('args["car"].getAuthor()'),
        message: "Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier"
    )]
    public function edit(Request $request, EntityManagerInterface $manager, Car $car): Response
    {
        
            $form = $this->createForm(CarType::class, $car); //récupérer le formulaire
            $form->handleRequest($request);

            if($form->isSubmitted() && $form->isValid())
            {

                // gestion des images 
                foreach($car->getImages() as $image)
                {
                    $image->setCar($car);
                    $manager->persist($image);
                }

                $manager->persist($car);
                $manager->flush();

                $this->addFlash(
                    'success',
                    "L'annonce <strong>".$car->getBrand()." ".$car->getModel()."</strong> a bien été modifiée!"
                );

                return $this->redirectToRoute('cars_show',[
                    'slug' => $car->getSlug()
                ]);

            }
        
        return $this->render("cars/edit.html.twig",[
            "car"=> $car,
            "myForm"=> $form->createView()
        ]);
    }

    /**
     * Supprimer une voiture
     *
     * @param Car $car
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route("cars/{slug}/delete", name:"cars_delete")]
    #[IsGranted(
        attribute: new Expression('(user === subject and is_granted("ROLE_USER")) or is_granted("ROLE_ADMIN")'),
        subject: new Expression('args["car"].getAuthor()'),
        message: "Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier"
    )]
    public function deleteCars(Car $car, EntityManagerInterface $manager): Response
    {
            $manager->remove($car);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>".$car->getBrand()." ".$car->getModel()."</strong> a bien été supprimée!"
            );

        return $this->redirectToRoute('cars_index');

        return $this->render('cars/delete.html.twig', [
            
        ]);
    }

    /**
     * Afficher chaque voiture
     *
     * @param string $slug
     * @param Car $car
     * @return Response
     */
    #[Route("/cars/{slug}", name:"cars_show")]
    public function show(string $slug, Car $car, CarRepository $repo): Response
    {
        //recup l'auteur de l'annonce
        $owner = $car->getAuthor();
        //recup les autres voitures de ce même auteur et les mettre dans un tab
        $otherCars = $owner->getCars()->toArray(); 
        //évite que la voiture de l'annonce apparaisse dans les suggestions
        $otherCars = array_filter($otherCars, function ($otherCar) use ($car) {
            return $otherCar !== $car;
        });
        
        return $this->render("cars/show.html.twig",[
            'car'=>$car,
            'owner'=>$owner,
            'otherCars' => $otherCars,
        ]);
    }
}

templates/cars/_collection.html.twig
{% block _car_images_widget %}
    {# Définition du champ car_images, la variable form correspond au champ car_images #}
    <p>Ici, vous pouvez ajouter vos propres images</p>
    {{form_widget(form)}}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Ajouter une image</button>
    </div> 

{% endblock %}

{% block _car_images_entry_row %}
    {{form_widget(form)}}
{% endblock %}

{% block _car_images_entry_widget %}
    <div class="form-group my-2" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{form_widget(form.url)}}
                        {{form_errors(form.url)}}
                    </div>
                    <div class="col">
                        {{form_widget(form.caption)}}
                        {{form_errors(form.caption)}}</div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" class="btn btn-danger" data-action="delete" data-target="#block_{{id}}">X</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/cars/edit.html.twig
{% extends "base.html.twig" %}


{% block title %}Mode Edition{% endblock %}

{% form_theme myForm 'cars/_collection.html.twig' %}

{% block body %}

    <div class="container mt-4">
        <h1>Modification de l'annonce : {{car.fullBrand}}</strong></h1>

        {{form_start(myForm)}}

            {{form_widget(myForm)}}
            <button type="submit" class="btn btn-warning mt-3">Modifier</button>


        {{form_end(myForm)}}
    </div>

{% endblock %}

{% block javascripts %}
    {{encore_entry_script_tags('car')}}
{% endblock %}

templates/cars/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Voitures{% endblock %}

{% block body %}
    <div class="container mt-4 ">
        <div class="row">
            <h1 class="mb-3">Consultez notre show-room</h1>
            <div class="row">
                <div class="col-md-6 mb-3">
                    <p>Découvrez notre showroom en ligne pour explorer notre impressionnante sélection de véhicules. Parcourez des modèles de haute qualité à des prix compétitifs, et trouvez la voiture de vos rêves dès aujourd'hui !</p>
                </div>
            </div>
            {% include "partials/cards.html.twig" %}
        </div>
    </div>
{% endblock %}

templates/cars/new.html.twig
{% extends "base.html.twig" %}


{% block title %}Création d'une fiche de vente{% endblock %}

{% form_theme myForm 'cars/_collection.html.twig' %}

{% block body %}
    <div class="container mt-4 ">
        <h1>Nouvelle voiture à vendre</h1>

        {{ form_start(myForm) }}


             {{form_widget(myForm)}}

            <button type="submit" class="btn btn-primary mt-3">Terminer</button>



        {{ form_end(myForm) }}
    </div>
{% endblock %}

{% block javascripts %}
    {{encore_entry_script_tags('car')}}
{% endblock %}

templates/cars/show.html.twig
{% extends "base.html.twig" %}

{% block title %}{{car.fullBrand}}{% endblock %}

{% block body %}
   <div class="container mt-4">
    <div class="row">
        <div class="col-md-6 mb-3">
            <h1 class="mb-0">{{car.model}}</h1>
            <h3 class="text-body-secondary">{{car.brand}}</h3>
            <hr>
            <div><strong>Modèle</strong>: {{car.model}}</div>
            <div><strong>Marque</strong>: {{car.brand}}</div>
            <div><strong>Kilométrage</strong>: {{car.km}} km</div>
            <div><strong>Année de mise en circulation</strong>: {{car.year}}</div>
            <div><strong>Nombre de propriétaires</strong>: {{car.owners}}</div>
            <div><strong>Carburant</strong>: {{car.carburant}}</div>
            <div><strong>Cylindrée</strong>: {{car.cylinder}} L</div>
            <div><strong>Puissance</strong>: {{car.power}} ch</div>
            <div><strong>Transmission</strong>: {{car.transmission}}</div>
            <div><strong>Description</strong>:{{car.content | raw | nl2br}}</div>
            <div><strong>Options</strong>:{{car.options | raw | nl2br}}</div>
            {% if (app.user and app.user == car.author) or is_granted('ROLE_ADMIN') %}
                <a href="{{path('cars_edit', {'slug':car.slug})}}" class="btn btn-warning m-2">Modification de l'annonce</a>
            {% endif %}
            {% if (app.user and app.user == car.author) or is_granted('ROLE_ADMIN') %}
                <a href="{{path('cars_delete', {'slug':car.slug})}}" class="btn btn-danger m-2">Suppression de l'annonce</a>
            {% endif %}
        </div>
        <div class="col md-6 mb-3">
            <div id="carImage">
                <div class="carCover">
                    <img src="{{car.coverImage}}" alt="couverture de {{car.brand}} {{car.model}}">
                </div>
            </div>
            <div><h1 id="price">{{car.price}} €</h1></div>
        </div>
    </div>
   </div>
    <div class="bd-example mt-5">
        <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
            <div class="carousel-indicators justify-content-start">
                {% for image in car.images %}
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{loop.index0}}" {% if loop.first %} class="active" aria-current="true" {% endif %} aria-label="Slide {{loop.index}}"></button>
            {% endfor %} 
            </div>
            <div class="carousel-inner">
                {% for image in car.images %}
                    <div class="carousel-item {% if loop.first %}active{% endif %}">
                        <img src="{{image.url}}" class="d-block w-100" alt="image de {{car.model}}">
                        <div class="carousel-caption d-none d-md-block" style="text-align: left;">
                                <h4>{{car.model}}</h4>
                                <h5>{{car.brand}}</h5>
                            <p>{{image.caption}}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>
    <div class="slidePage">
        <div class="container mt-5">
            <h1>Profil de l'utilisateur</h1>
            <div class="row mt-4">
                <div class="col-md-1 ownerAvatar">
                {% include "partials/avatar.html.twig" %}
                </div>
                <div class="col-md-10">
                    <h3>{{owner.lastName}}</h3>
                    <h4 class="text-body-secondary">{{owner.firstName}}</h4>
                    <hr>
                    <div class="text-end mb-3"><p>{{owner.introduction}}</p>
                        <figcaption class="blockquote-footer">
                            {{owner.firstName}} {{owner.lastName}} for<cite title="Source Title">Sell Your Car</cite>
                        </figcaption>
                    </div>
                    <p>{{owner.description | raw}}</p>
                </div>
            </div>
            <h1 class="mt-3 mb-4">Du même vendeur</h1>
            <div class="row">
                {% for otherCar in otherCars %}
                    {% set url = path('cars_show', {'slug':otherCar.slug}) %}
                    <div class="col-md-4">
                        <div class="card cardHover mb-3">
                            <div class="card-header text-center">
                                {{otherCar.km}} km, <strong>{{otherCar.price}}€</strong>
                            </div>
                            <a href="{{url}}">
                                <img src="{{otherCar.coverImage}}" alt="image de la voiture {{otherCar.model}}" class="starsimg">
                            </a>
                            <div class="card-body">
                                <h3 class="card-title">{{otherCar.model}}</h3>
                                <h5 class="card-title">{{otherCar.brand}}</h5>
                                <a href="{{url}}" class="btn btn-primary">En savoir plus</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}